// The initialMovies array is now expanded with all the details for the modal
export const initialMovies = [
  // Latest
  {
    id: 1,
    title: "Dune: Part Two",
    genre: "Sci-Fi",
    year: 2024,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760259948/samples/balloons.jpg",
    rating: 8.8,
    runtime: 166,
    description:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
    platforms: [
      { name: "YouTube", url: "https://www.youtube.com/watch?v=U2Qp5pL3ovA" },
      { name: "Prime Video", url: "https://www.primevideo.com/detail/0S3A44S0KH40GG0Y64243627A0/" },
    ],
  },
  {
    id: 2,
    title: "A Minecraft Movie",
    genre: "Action",
    year: 2025,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760260489/minecraft_sdioft.webp",
    rating: 7.5,
    runtime: 120,
    description:
      "The malevolent Ender Dragon sets out on a path of destruction, prompting a young girl and her group of unlikely adventurers to set out to save the Overworld.",
    director: "Jared Hess",
    cast: ["Jason Momoa", "Jack Black", "Emma Myers"],
    platforms: [{ name: "Theaters", url: "#" }],
  },
  {
    id: 3,
    title: "F1: The Movie",
    genre: "Action",
    year: 2025,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760260499/F1-The-Movie_zr1xgb.webp",
    rating: 8.1,
    runtime: 130,
    description:
      "A former Formula 1 driver returns to the sport to mentor a younger driver at the prestigious Apex team.",
    director: "Joseph Kosinski",
    cast: ["Brad Pitt", "Damson Idris", "Kerry Condon"],
    platforms: [{ name: "Apple TV+", url: "https://tv.apple.com/" }],
  },
  {
    id: 4,
    title: "Godzilla x Kong",
    genre: "Action",
    year: 2024,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760260502/godzilla_edhnmj.webp",
    rating: 6.5,
    runtime: 115,
    description:
      "The two titans, Godzilla and Kong, must unite against a colossal undiscovered threat hidden within our world.",
    director: "Adam Wingard",
    cast: ["Rebecca Hall", "Brian Tyree Henry", "Dan Stevens"],
    platforms: [{ name: "Prime Video", url: "https://www.primevideo.com/detail/0STTE5S46Y15B4F05Y352528S3/" }],
  },
  {
    id: 5,
    title: "Inside Out 2",
    genre: "Comedy",
    year: 2024,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760264464/p_insideout_19751_af12286c_g8utut.webp",
    rating: 8.0,
    runtime: 96,
    description:
      "Riley's mind undergoes a sudden demolition to make room for something entirely unexpected: new Emotions!",
    director: "Kelsey Mann",
    cast: ["Amy Poehler", "Maya Hawke", "Phyllis Smith"],
    platforms: [{ name: "Disney+", url: "https://www.disneyplus.com/movies/inside-out-2/50f25212-332e-4360-9f17-d950c744883e" }],
  },
  {
    id: 41,
    title: "Gladiator 2",
    genre: "Action",
    year: 2024,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760260500/galdiator_zl6uww.webp",
    rating: 8.3,
    runtime: 150,
    description:
      "Lucius, the son of Lucilla and nephew of Commodus, is followed as he continues his journey as a grown man, inspired by Maximus's sacrifice.",
    director: "Ridley Scott",
    cast: ["Paul Mescal", "Denzel Washington", "Pedro Pascal"],
    platforms: [{ name: "Theaters", url: "#" }],
  },

  // Action
  {
    id: 6,
    title: "Mad Max: Fury Road",
    genre: "Action",
    year: 2015,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760259949/samples/outdoor-woman.jpg",
    rating: 8.1,
    runtime: 120, // Added runtime for consistency
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the help of a group of female prisoners and a drifter named Max.",
    director: "George Miller",
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
    platforms: [
      { name: "Prime Video", url: "https://www.primevideo.com/detail/0HDRG6I25MA036A20720O362U7/" },
    ],
  },
  {
    id: 7,
    title: "John Wick: Chapter 4",
    genre: "Action",
    year: 2023,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760259948/samples/balloons.jpg",
    rating: 7.8,
    runtime: 169,
    description:
      "John Wick uncovers a path to defeating The High Table, facing off against a new enemy with powerful alliances across the globe.",
    director: "Chad Stahelski",
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård"],
    platforms: [{ name: "Starz", url: "https://www.starz.com/us/en/movies/john-wick-chapter-4-2023-81239" }],
  },
  {
    id: 8,
    title: "The Dark Knight",
    genre: "Action",
    year: 2008,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760262520/fd2a62ebf8534a10465dfc63ea11635bd42ed1692ad3af11d5e83ab553e3d0ae_pn8zd9.webp",
    rating: 9.0,
    runtime: 152,
    description:
      "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest tests of his ability to fight injustice.",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    platforms: [{ name: "Max", url: "https://www.max.com/movies/the-dark-knight/8d3db518-b752-4460-a24c-5353106d7d65" }],
  },
  {
    id: 9,
    title: "Die Hard",
    genre: "Action",
    year: 1988,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760262563/fposter_small_wall_texture_square_product_600x600_gy44bm.webp",
    rating: 8.2,
    runtime: 132,
    description:
      "An NYPD officer tries to save his wife and several others taken hostage by terrorists during a Christmas party at the Nakatomi Plaza.",
    director: "John McTiernan",
    cast: ["Bruce Willis", "Alan Rickman", "Bonnie Bedelia"],
    platforms: [{ name: "Hulu", url: "https://www.hulu.com/movie/die-hard-2858d613-305f-4025-a8d6-fc6c05a6d328" }],
  },
  {
    id: 10,
    title: "Top Gun: Maverick",
    genre: "Action",
    year: 2022,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760262614/81DtS0nituL_ghwn3p.webp",
    rating: 8.3,
    runtime: 130,
    description:
      "After thirty years of service as a top naval aviator, Pete 'Maverick' Mitchell is where he belongs, pushing the envelope as a courageous test pilot.",
    director: "Joseph Kosinski",
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
    platforms: [{ name: "Prime Video", url: "https://www.primevideo.com/detail/0J2QR13ZZQ43FGX1C00G2M4320/" }],
  },

  // Comedy
  {
    id: 11,
    title: "Superbad",
    genre: "Comedy",
    year: 2007,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760264354/b4232cf0f135f566ddf63f8c10ba9427_blobmc.webp",
    rating: 7.6,
    runtime: 113,
    description:
      "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
    director: "Greg Mottola",
    cast: ["Jonah Hill", "Michael Cera", "Christopher Mintz-Plasse"],
    platforms: [
      { name: "Netflix", url: "https://www.netflix.com/title/70058021" },
      { name: "Prime Video", url: "https://www.primevideo.com/detail/0NL1CR4T7N5A3A051A051A3I4U/" },
    ],
  },
  {
    id: 12,
    title: "Booksmart",
    genre: "Comedy",
    year: 2019,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760262750/MV5BMjEzMjcxNjA2Nl5BMl5BanBnXkFtZTgwMjAxMDM2NzM_q26hnw.webp",
    rating: 7.2,
    runtime: 102,
    description:
      "On the eve of their high school graduation, two academic superstars realize they should have worked less and played more.",
    director: "Olivia Wilde",
    cast: ["Kaitlyn Dever", "Beanie Feldstein", "Jessica Williams"],
    platforms: [{ name: "Prime Video", url: "https://www.primevideo.com/detail/0OHG6B98675P6GC6C2C1H6Q010/" }],
  },
  {
    id: 13,
    title: "Anchorman",
    genre: "Comedy",
    year: 2004,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760262783/COVERM_8391378b-04f1-44e9-90b6-f153985f04dd_01_tlegnn.webp",
    rating: 7.2,
    runtime: 94,
    description:
      "In the 1970s, an anchorman's stint as San Diego's top-rated newsreader is challenged when an ambitious woman is hired as a new anchor.",
    director: "Adam McKay",
    cast: ["Will Ferrell", "Christina Applegate", "Paul Rudd"],
    platforms: [{ name: "Paramount+", url: "https://www.paramountplus.com/movies/anchorman-the-legend-of-ron-burgundy/y_L5sDGg1Jc5d1sU1TGs2I34LMfLGIoM/" }],
  },
  {
    id: 14,
    title: "Bridesmaids",
    genre: "Comedy",
    year: 2011,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760264513/Bridesmaids_website_banner_1600x_opdequ.webp",
    rating: 6.8,
    runtime: 125,
    description:
      "Competition between the maid of honor and a bridesmaid, over who is the bride's best friend, threatens to upend the life of an out-of-work pastry chef.",
    director: "Paul Feig",
    cast: ["Kristen Wiig", "Maya Rudolph", "Rose Byrne"],
    platforms: [{ name: "Peacock", url: "https://www.peacocktv.com/watch/asset/movies/bridesmaids-unrated/b7b13483-36ea-3904-89f5-3b992f392b45" }],
  },
  {
    id: 15,
    title: "Step Brothers",
    genre: "Comedy",
    year: 2008,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760264535/MV5BYWNiOGZkOTgtNGMzMC00MDg5LTliM2UtN2VjMDI3N2ViOWE5XkEyXkFqcGc_xifoo4.webp",
    rating: 6.9,
    runtime: 98,
    description:
      "Two aimless middle-aged losers still living at home are forced against their will to become roommates when their parents marry.",
    director: "Adam McKay",
    cast: ["Will Ferrell", "John C. Reilly", "Mary Steenburgen"],
    platforms: [{ name: "Hulu", url: "https://www.hulu.com/movie/step-brothers-3b6ae281-d419-4672-91bf-2a3b2b3b05f2" }],
  },

  // Drama
  {
    id: 16,
    title: "The Godfather",
    genre: "Drama",
    year: 1972,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760264431/411bvEU9pqL_bfmze1.webp",
    rating: 9.2,
    runtime: 175,
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    platforms: [{ name: "Paramount+", url: "https://www.paramountplus.com/movies/the-godfather/n3_rwf9R96sHrklz5g58vMFaUo03YAdN/" }],
  },
  {
    id: 17,
    title: "Parasite",
    genre: "Drama",
    year: 2019,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760259943/samples/landscapes/landscape-panorama.jpg",
    rating: 8.6,
    runtime: 132,
    description:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    director: "Bong Joon Ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    platforms: [{ name: "Max", url: "https://www.max.com/movies/parasite/65f6b758-c024-42ea-9c02-e2a265631f25" }],
  },
  {
    id: 18,
    title: "The Shawshank Redemption",
    genre: "Drama",
    year: 1994,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760264387/The-Shawshank-Redemption-Movie-Poster-11-x-17_88c44117-2ab3-4eae-9aec-3caca2cb23ea.02c9417ed40cf599996bce3ba7fbd085_ly7xtt.webp",
    rating: 9.3,
    runtime: 142,
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    platforms: [{ name: "Prime Video", url: "https://www.primevideo.com/detail/0FS1R1ADD43QGJ52W9R09528A7/" }],
  },
  {
    id: 19,
    title: "Pulp Fiction",
    genre: "Drama",
    year: 1994,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760259935/samples/animals/cat.jpg",
    rating: 8.9,
    runtime: 154,
    description:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    platforms: [{ name: "Max", url: "https://www.max.com/movies/pulp-fiction/95662a86-d249-436f-b88a-3a72688086a6" }],
  },
  {
    id: 20,
    title: "Forrest Gump",
    genre: "Drama",
    year: 1994,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760262859/il_300x300.6744519309_4xyo_wihkxe.webp",
    rating: 8.8,
    runtime: 142,
    description:
      "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
    director: "Robert Zemeckis",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    platforms: [{ name: "Paramount+", url: "https://www.paramountplus.com/movies/forrest-gump/5_C22g7xR0mD_u6B_zddMo16a3G75E_/" }],
  },

  // Horror
  {
    id: 21,
    title: "Get Out",
    genre: "Horror",
    year: 2017,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760259933/sample.jpg",
    rating: 7.7,
    runtime: 104,
    description:
      "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
    director: "Jordan Peele",
    cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
    platforms: [{ name: "Netflix", url: "https://www.netflix.com/title/80149258" }],
  },
  {
    id: 22,
    title: "Hereditary",
    genre: "Horror",
    year: 2018,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263211/Hereditary_rohv4d.webp",
    rating: 7.3,
    runtime: 127,
    description:
      "A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother.",
    director: "Ari Aster",
    cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro"],
    platforms: [{ name: "Max", url: "https://www.max.com/movies/hereditary/03337a7d-81c8-466d-886f-23a63690e80a" }],
  },
  {
    id: 23,
    title: "The Shining",
    genre: "Horror",
    year: 1980,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263240/81nwnHTcV2L_b1pqxj.webp",
    rating: 8.4,
    runtime: 146,
    description:
      "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings.",
    director: "Stanley Kubrick",
    cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd"],
    platforms: [{ name: "Max", url: "https://www.max.com/movies/the-shining/15a7f29f-3506-4475-b9b4-2b634354b51a" }],
  },
  {
    id: 24,
    title: "The Exorcist",
    genre: "Horror",
    year: 1973,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263272/william-peter-blatty-the-exorcist-y5925rhhtyd2lb93_tkwkjo.webp",
    rating: 8.0,
    runtime: 122,
    description:
      "When a 12-year-old girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.",
    director: "William Friedkin",
    cast: ["Ellen Burstyn", "Max von Sydow", "Linda Blair"],
    platforms: [{ name: "Prime Video", url: "https://www.primevideo.com/detail/0H8Y05I15A038Y05I15A038Y8U/" }],
  },
  {
    id: 25,
    title: "It",
    genre: "Horror",
    year: 2017,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263306/MV5BZGZmOTZjNzUtOTE4OS00OGM3LWJiNGEtZjk4Yzg2M2Q1YzYxXkEyXkFqcGc_wizxup.webp",
    rating: 7.3,
    runtime: 135,
    description:
      "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry.",
    director: "Andy Muschietti",
    cast: ["Jaeden Martell", "Bill Skarsgård", "Finn Wolfhard"],
    platforms: [{ name: "Netflix", url: "https://www.netflix.com/title/80175529" }],
  },

  // Romance
  {
    id: 26,
    title: "La La Land",
    genre: "Romance",
    year: 2016,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263480/91mC_2DBweL_zk8yri.webp",
    rating: 8.0,
    runtime: 128,
    description:
      "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    director: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone", "John Legend"],
    platforms: [{ name: "Netflix", url: "https://www.netflix.com/title/80095365" }],
  },
  {
    id: 27,
    title: "Portrait of a Lady on Fire",
    genre: "Romance",
    year: 2019,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263445/image_egv3wf.webp",
    rating: 8.1,
    runtime: 122,
    description:
      "On an isolated island in Brittany at the end of the eighteenth century, a female painter is obliged to paint a wedding portrait of a young woman.",
    director: "Céline Sciamma",
    cast: ["Noémie Merlant", "Adèle Haenel", "Luàna Bajrami"],
    platforms: [{ name: "Hulu", url: "https://www.hulu.com/movie/portrait-of-a-lady-on-fire-2358362e-a611-436f-8557-0b19e448373e" }],
  },
  {
    id: 28,
    title: "The Notebook",
    genre: "Romance",
    year: 2004,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263418/41q3LCMOr7L_awbf9t.webp",
    rating: 7.8,
    runtime: 123,
    description:
      "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated because of their social differences.",
    director: "Nick Cassavetes",
    cast: ["Ryan Gosling", "Rachel McAdams", "James Garner"],
    platforms: [{ name: "Hulu", url: "https://www.hulu.com/movie/the-notebook-35515712-e565-4f7f-9457-3d9697956441" }],
  },
  {
    id: 29,
    title: "When Harry Met Sally...",
    genre: "Romance",
    year: 1989,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263385/41a8zOZ1ItL_buoea6.webp",
    rating: 7.6,
    runtime: 95,
    description:
      "Harry and Sally have known each other for years, and are very good friends, but they fear sex would ruin the friendship.",
    director: "Rob Reiner",
    cast: ["Billy Crystal", "Meg Ryan", "Carrie Fisher"],
    platforms: [{ name: "Netflix", url: "https://www.netflix.com/title/60000350" }],
  },
  {
    id: 30,
    title: "Pride & Prejudice",
    genre: "Romance",
    year: 2005,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263336/hollywood-the-films-poster-on-display-at-the-variety-screening-series-of-pride-prejudice-at-the_qtfxlo.webp",
    rating: 7.8,
    runtime: 129,
    description:
      "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy. But Mr. Darcy reluctantly finds himself falling in love with a woman beneath his class.",
    director: "Joe Wright",
    cast: ["Keira Knightley", "Matthew Macfadyen", "Brenda Blethyn"],
    platforms: [{ name: "Netflix", url: "https://www.netflix.com/title/70032609" }],
  },

  // Sci-Fi
  {
    id: 31,
    title: "Blade Runner 2049",
    genre: "Sci-Fi",
    year: 2017,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263636/blade_runner2049_whv_keyart_o74jjr.webp",
    rating: 8.0,
    runtime: 164,
    description:
      "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    director: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
    platforms: [{ name: "Hulu", url: "https://www.hulu.com/movie/blade-runner-2049-dd00e309-858f-430c-8c28-e04efe6a17b8" }],
  },
  {
    id: 32,
    title: "Arrival",
    genre: "Sci-Fi",
    year: 2016,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263610/arrivals-sign-modern-airport-terminal_233473-4080_yahsb0.webp",
    rating: 7.9,
    runtime: 116,
    description:
      "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    director: "Denis Villeneuve",
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
    platforms: [{ name: "Paramount+", url: "https://www.paramountplus.com/movies/arrival/1YhPJK1XFV8Yx8CUE6dGzY8dG8X484K3/" }],
  },
  {
    id: 33,
    title: "Interstellar",
    genre: "Sci-Fi",
    year: 2014,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263578/MV5BNmIwM2E3YjMtYWUxYi00M2ZkLWFmMzktZWFiYTU4MGM2YTk2XkEyXkFqcGc_rqsp1o.webp",
    rating: 8.6,
    runtime: 169,
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    platforms: [{ name: "Prime Video", url: "https://www.primevideo.com/detail/0I846C82S2V1W2345T1N252Q86/" }],
  },
  {
    id: 34,
    title: "The Matrix",
    genre: "Sci-Fi",
    year: 1999,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263548/the-matrix-reloaded-neo-keanu-reeves-stopping-bullets_kcseri.webp",
    rating: 8.7,
    runtime: 136,
    description:
      "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    director: "Lana Wachowski, Lilly Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    platforms: [{ name: "Max", url: "https://www.max.com/movies/the-matrix/e7a3316e-5f8f-4e1b-a5d9-33d3c7c4e532" }],
  },
  {
    id: 35,
    title: "Alien",
    genre: "Sci-Fi",
    year: 1979,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263518/360_F_360926733_iqohoHnivYLgTHhxv15yn5Rm6dFBVHx4_pf6v1v.webp",
    rating: 8.4,
    runtime: 117,
    description:
      "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.",
    director: "Ridley Scott",
    cast: ["Sigourney Weaver", "Tom Skerritt", "John Hurt"],
    platforms: [{ name: "Hulu", url: "https://www.hulu.com/movie/alien-b0340b90-d861-4d43-888e-17e4f3a743a3" }],
  },

  // Thriller
  {
    id: 36,
    title: "The Silence of the Lambs",
    genre: "Thriller",
    year: 1991,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263751/706556_poster_l_mg90hi.webp",
    rating: 8.6,
    runtime: 118,
    description:
      "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    director: "Jonathan Demme",
    cast: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
    platforms: [{ name: "Max", url: "https://www.max.com/movies/the-silence-of-the-lambs/e1e1293a-86c8-4e13-90d0-0f2a74c7283c" }],
  },
  {
    id: 37,
    title: "A Quiet Place",
    genre: "Thriller",
    year: 2018,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263727/910aiWLEbUL_lmhd9m.webp",
    rating: 7.5,
    runtime: 90,
    description:
      "A family struggles for survival in a world where most humans have been killed by blind but noise-sensitive creatures.",
    director: "John Krasinski",
    cast: ["Emily Blunt", "John Krasinski", "Millicent Simmonds"],
    platforms: [{ name: "Paramount+", url: "https://www.paramountplus.com/movies/a-quiet-place/wK150bA1g8PAg2KdaJk0ahAqP4CCmQzP/" }],
  },
  {
    id: 38,
    title: "Se7en",
    genre: "Thriller",
    year: 1995,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263707/pfilm1161-se7en-movie-poster-500x500h_u4ypcz.webp",
    rating: 8.6,
    runtime: 127,
    description:
      "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    director: "David Fincher",
    cast: ["Morgan Freeman", "Brad Pitt", "Kevin Spacey"],
    platforms: [{ name: "Max", url: "https://www.max.com/movies/se7en/05d01150-e555-4673-a26f-99a38f4d1e20" }],
  },
  {
    id: 39,
    title: "Gone Girl",
    genre: "Thriller",
    year: 2014,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760263684/3510975_j0b4mo.webp",
    rating: 8.1,
    runtime: 149,
    description:
      "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    director: "David Fincher",
    cast: ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris"],
    platforms: [{ name: "Hulu", url: "https://www.hulu.com/movie/gone-girl-dd53b71c-7622-411a-a53b-f1f3b3974c8b" }],
  },
  {
    id: 40,
    title: "Knives Out",
    genre: "Thriller",
    year: 2019,
    image: "https://res.cloudinary.com/dwioxbbrl/image/upload/v1760260237/Knives-Out-jpg_aqzocn.webp",
    rating: 7.9,
    runtime: 130,
    description:
      "A detective investigates the death of a patriarch of an eccentric, combative family.",
    director: "Rian Johnson",
    cast: ["Daniel Craig", "Chris Evans", "Ana de Armas"],
    platforms: [{ name: "Prime Video", url: "https://www.primevideo.com/detail/0L4W05I15A038W05I15A038W8U/" }],
  },
];

export const dummySuggestions = [
  {
    id: "s1",
    title: "The Shawshank Redemption",
    review:
      "An absolute masterpiece about hope and friendship. The storytelling is phenomenal and it never gets old no matter how many times you watch it.",
    suggestedBy: "MovieBuff123",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), // 3 hours ago
  },
  {
    id: "s2",
    title: "Inception",
    review:
      "Mind-bending thriller that keeps you guessing until the very end. Christopher Nolan's best work!",
    suggestedBy: "FilmFanatic",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(), // 6 hours ago
    image: "inception.jpg",
  },
  {
    id: "s3",
    title: "Parasite",
    review:
      "A brilliant social commentary wrapped in a thrilling story. Bong Joon-Ho is a genius filmmaker.",
    suggestedBy: "CinemaLover",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
  },
];